#!/usr/bin/env python3
"""Reference spreadsheet formula engine.

Reads a JSON grid from stdin, evaluates every formula cell, and writes the
fully-computed grid as JSON to stdout.

Contract:  python reference_engine.py < input.json > out.json

This file is the authoritative definition of the engine's semantics. The hidden
golden outputs are generated by running compute() over each fixture input, so the
reference is correct by construction. See instruction.md for the human-readable
specification that mirrors the behavior implemented here.
"""

import sys
import io
import json
import math
import re
from decimal import Decimal, ROUND_HALF_UP, localcontext


# --------------------------------------------------------------------------- #
# Value model
# --------------------------------------------------------------------------- #
# Internal value types produced during evaluation:
#   * int / float          -- numbers (bool is NOT treated as a number here)
#   * bool                 -- TRUE / FALSE
#   * str                  -- text
#   * BLANK (sentinel)     -- an empty cell / empty reference target
#   * Error                -- an error value carrying an exact token string
#   * RangeValue           -- the value of a range expression (A1:B3)

ERROR_TOKENS = {
    "#DIV/0!", "#VALUE!", "#NAME?", "#REF!", "#NUM!", "#CIRCULAR!", "#ERROR!",
}


class Error:
    __slots__ = ("code",)

    def __init__(self, code):
        self.code = code

    def __repr__(self):
        return "Error(%r)" % self.code


class _Blank:
    __slots__ = ()

    def __repr__(self):
        return "BLANK"


BLANK = _Blank()


class RangeValue:
    """A materialized rectangular range: cells flattened row-major."""

    __slots__ = ("cells",)

    def __init__(self, cells):
        self.cells = cells  # list of internal scalar values, row-major


def is_error(v):
    return isinstance(v, Error)


# --------------------------------------------------------------------------- #
# Address helpers
# --------------------------------------------------------------------------- #
_ADDR_RE = re.compile(r"^\$?([A-Za-z]+)\$?([0-9]+)$")


def col_to_index(letters):
    """Bijective base-26: A->1, Z->26, AA->27, ..."""
    idx = 0
    for ch in letters.upper():
        idx = idx * 26 + (ord(ch) - ord("A") + 1)
    return idx


def index_to_col(idx):
    letters = ""
    while idx > 0:
        idx, rem = divmod(idx - 1, 26)
        letters = chr(ord("A") + rem) + letters
    return letters


def parse_addr(key):
    """Parse a cell key like 'A1' or '$B$2' -> (col_index, row_index)."""
    m = _ADDR_RE.match(key)
    if not m:
        raise ValueError("bad address: %r" % key)
    return col_to_index(m.group(1)), int(m.group(2))


def addr_str(col, row):
    return index_to_col(col) + str(row)


# --------------------------------------------------------------------------- #
# Tokenizer
# --------------------------------------------------------------------------- #
# Token kinds: ('num', value) ('str', value) ('ref', (col,row))
#              ('name', UPPER) ('op', symbol)
_TOKEN_RE = re.compile(
    r"""
      \s+                                   # whitespace (skipped)
    | (?P<num>  \d+\.\d+ | \d+\. | \.\d+ | \d+ )
    | (?P<str>  " (?: [^"] | "" )* " )
    | (?P<ref>  \$?[A-Za-z]+\$?[0-9]+ )
    | (?P<name> [A-Za-z_][A-Za-z0-9_.]* )
    | (?P<op>   <> | <= | >= | [-+*/^&=<>():,] )
    """,
    re.VERBOSE,
)


class ParseError(Exception):
    pass


def tokenize(text):
    tokens = []
    pos = 0
    n = len(text)
    while pos < n:
        m = _TOKEN_RE.match(text, pos)
        if not m or m.end() == pos:
            raise ParseError("bad character at %d: %r" % (pos, text[pos:pos + 8]))
        pos = m.end()
        if m.lastgroup is None:
            continue  # whitespace
        kind = m.lastgroup
        val = m.group()
        if kind == "num":
            tokens.append(("num", float(val) if "." in val else int(val)))
        elif kind == "str":
            inner = val[1:-1].replace('""', '"')
            tokens.append(("str", inner))
        elif kind == "ref":
            tokens.append(("ref", parse_addr(val)))
        elif kind == "name":
            tokens.append(("name", val.upper()))
        elif kind == "op":
            tokens.append(("op", val))
    return tokens


# --------------------------------------------------------------------------- #
# Parser (precedence climbing)
# --------------------------------------------------------------------------- #
# AST nodes (tuples):
#   ('num', v) ('str', v) ('bool', v)
#   ('ref', (col,row))
#   ('range', (c1,r1), (c2,r2))
#   ('unary', op, node)
#   ('binary', op, left, right)
#   ('func', NAME, [args])
#   ('nameerr', NAME)          -- bareword that is not TRUE/FALSE/function
#
# Binding powers (higher binds tighter). Binary operators are left-associative.
_BINDING = {
    "=": 1, "<>": 1, "<": 1, ">": 1, "<=": 1, ">=": 1,
    "&": 2,
    "+": 3, "-": 3,
    "*": 4, "/": 4,
    "^": 5,
}
_UNARY_BP = 6  # unary +/- bind tighter than ^  => -2^2 == (-2)^2 == 4


class Parser:
    def __init__(self, tokens):
        self.toks = tokens
        self.i = 0

    def peek(self):
        return self.toks[self.i] if self.i < len(self.toks) else None

    def next(self):
        t = self.toks[self.i]
        self.i += 1
        return t

    def expect_op(self, sym):
        t = self.peek()
        if t is None or t[0] != "op" or t[1] != sym:
            raise ParseError("expected %r" % sym)
        self.next()

    def parse(self):
        node = self.parse_expr(0)
        if self.i != len(self.toks):
            raise ParseError("trailing tokens")
        return node

    def parse_expr(self, min_bp):
        left = self.parse_prefix()
        while True:
            t = self.peek()
            if t is None or t[0] != "op":
                break
            op = t[1]
            bp = _BINDING.get(op)
            if bp is None or bp < min_bp:
                break
            self.next()
            right = self.parse_expr(bp + 1)  # +1 => left associative
            left = ("binary", op, left, right)
        return left

    def parse_prefix(self):
        t = self.peek()
        if t is not None and t[0] == "op" and t[1] in ("+", "-"):
            self.next()
            operand = self.parse_expr(_UNARY_BP)
            return ("unary", t[1], operand)
        return self.parse_atom()

    def parse_atom(self):
        t = self.peek()
        if t is None:
            raise ParseError("unexpected end")
        kind = t[0]
        if kind == "num":
            self.next()
            return ("num", t[1])
        if kind == "str":
            self.next()
            return ("str", t[1])
        if kind == "ref":
            self.next()
            start = t[1]
            nt = self.peek()
            if nt is not None and nt[0] == "op" and nt[1] == ":":
                self.next()
                nt2 = self.peek()
                if nt2 is None or nt2[0] != "ref":
                    raise ParseError("expected ref after ':'")
                self.next()
                return ("range", start, nt2[1])
            return ("ref", start)
        if kind == "name":
            self.next()
            name = t[1]
            nt = self.peek()
            if nt is not None and nt[0] == "op" and nt[1] == "(":
                self.next()
                args = self.parse_args()
                self.expect_op(")")
                return ("func", name, args)
            if name in ("TRUE", "FALSE"):
                return ("bool", name == "TRUE")
            return ("nameerr", name)
        if kind == "op" and t[1] == "(":
            self.next()
            node = self.parse_expr(0)
            self.expect_op(")")
            return node
        raise ParseError("unexpected token %r" % (t,))

    def parse_args(self):
        args = []
        if self.peek() is not None and self.peek() == ("op", ")"):
            return args
        args.append(self.parse_expr(0))
        while self.peek() == ("op", ","):
            self.next()
            args.append(self.parse_expr(0))
        return args


def parse_formula(text):
    return Parser(tokenize(text)).parse()


# --------------------------------------------------------------------------- #
# Coercions
# --------------------------------------------------------------------------- #
def format_number(x):
    """Format a number for text contexts: integral -> no decimal point."""
    if isinstance(x, bool):
        return "TRUE" if x else "FALSE"
    if isinstance(x, int):
        return str(x)
    if isinstance(x, float):
        if x != x or x in (float("inf"), float("-inf")):
            return str(x)
        if x.is_integer():
            return str(int(x))
        return repr(x)
    return str(x)


def coerce_number(v):
    if is_error(v):
        return v
    if isinstance(v, bool):
        return 1 if v else 0
    if isinstance(v, (int, float)):
        return v
    if v is BLANK:
        return 0
    return Error("#VALUE!")  # text or range


def coerce_text(v):
    if is_error(v):
        return v
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if v is BLANK:
        return ""
    if isinstance(v, str):
        return v
    if isinstance(v, (int, float)):
        return format_number(v)
    return Error("#VALUE!")  # range


def coerce_bool(v):
    """Boolean scalar context (IF condition, AND/OR/NOT scalar args)."""
    if is_error(v):
        return v
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        return v != 0
    if v is BLANK:
        return False
    return Error("#VALUE!")  # text or range


def type_class(v):
    if isinstance(v, bool):
        return "bool"
    if isinstance(v, (int, float)):
        return "num"
    if isinstance(v, str):
        return "text"
    if v is BLANK:
        return "blank"
    return "range"


# --------------------------------------------------------------------------- #
# Operators
# --------------------------------------------------------------------------- #
def op_arith(op, a, b):
    a = coerce_number(a)
    if is_error(a):
        return a
    b = coerce_number(b)
    if is_error(b):
        return b
    if op == "+":
        return a + b
    if op == "-":
        return a - b
    if op == "*":
        return a * b
    if op == "/":
        if b == 0:
            return Error("#DIV/0!")
        return a / b
    if op == "^":
        return op_power(a, b)
    raise ParseError("bad op")


def op_power(a, b):
    if a < 0 and not float(b).is_integer():
        return Error("#NUM!")
    try:
        r = a ** b
    except (OverflowError, ValueError, ZeroDivisionError):
        return Error("#NUM!")
    if isinstance(r, complex):
        return Error("#NUM!")
    if isinstance(r, float) and (r != r or r in (float("inf"), float("-inf"))):
        return Error("#NUM!")
    return r


def op_unary(op, v):
    v = coerce_number(v)
    if is_error(v):
        return v
    return -v if op == "-" else +v


def op_concat(a, b):
    a = coerce_text(a)
    if is_error(a):
        return a
    b = coerce_text(b)
    if is_error(b):
        return b
    return a + b


def values_equal(a, b):
    ta, tb = type_class(a), type_class(b)
    if ta == "blank" and tb == "blank":
        return True
    if ta == "blank":
        if tb == "num":
            return 0 == b
        if tb == "text":
            return b == ""
        return False  # blank vs bool
    if tb == "blank":
        return values_equal(b, a)
    if ta != tb:
        return False
    if ta == "text":
        return a.upper() == b.upper()
    return a == b  # num or bool


def op_compare(op, a, b):
    if is_error(a):
        return a
    if is_error(b):
        return b
    if isinstance(a, RangeValue) or isinstance(b, RangeValue):
        return Error("#VALUE!")
    if op == "=":
        return values_equal(a, b)
    if op == "<>":
        return not values_equal(a, b)
    # ordering: <, >, <=, >=
    # Type classes for ordering are number, text, and boolean. A blank operand
    # adopts the OTHER operand's type (number -> 0, text -> ""). Any remaining
    # cross-class ordering (including boolean vs number/text) is #VALUE!.
    ta, tb = type_class(a), type_class(b)
    if ta == "blank" and tb == "blank":
        a, b, ta, tb = 0, 0, "num", "num"
    elif ta == "blank":
        if tb == "num":
            a, ta = 0, "num"
        elif tb == "text":
            a, ta = "", "text"
        else:  # bool
            return Error("#VALUE!")
    elif tb == "blank":
        if ta == "num":
            b, tb = 0, "num"
        elif ta == "text":
            b, tb = "", "text"
        else:  # bool
            return Error("#VALUE!")
    if ta != tb:
        return Error("#VALUE!")
    if ta == "bool":
        a, b = (1 if a else 0), (1 if b else 0)
    elif ta == "text":
        a, b = a.upper(), b.upper()
    if op == "<":
        return a < b
    if op == ">":
        return a > b
    if op == "<=":
        return a <= b
    if op == ">=":
        return a >= b
    raise ParseError("bad op")


# --------------------------------------------------------------------------- #
# Functions
# --------------------------------------------------------------------------- #
# Arity spec: exact int, or (min, None) for variadic-min.
FUNC_ARITY = {
    "SUM": (1, None), "AVERAGE": (1, None), "MIN": (1, None), "MAX": (1, None),
    "COUNT": (1, None), "COUNTA": (1, None), "CONCAT": (1, None),
    "AND": (1, None), "OR": (1, None),
    "IF": 3, "IFERROR": 2, "NOT": 1,
    "ROUND": 2, "MOD": 2, "POWER": 2, "LEFT": 2, "RIGHT": 2, "MID": 3,
    "ABS": 1, "INT": 1, "SQRT": 1, "LEN": 1,
    "UPPER": 1, "LOWER": 1, "TRIM": 1,
}


def check_arity(name, argc):
    spec = FUNC_ARITY[name]
    if isinstance(spec, tuple):
        lo, hi = spec
        if argc < lo:
            return False
        if hi is not None and argc > hi:
            return False
        return True
    return argc == spec


def first_arg_error(vals):
    """Return the first error appearing in args (scalars or inside ranges),
    scanning left-to-right and row-major. This drives error precedence."""
    for v in vals:
        if is_error(v):
            return v
        if isinstance(v, RangeValue):
            for c in v.cells:
                if is_error(c):
                    return c
    return None


def fn_sum(vals):
    total = 0
    for v in vals:
        if isinstance(v, RangeValue):
            for c in v.cells:
                if isinstance(c, bool):
                    continue
                if isinstance(c, (int, float)):
                    total += c
        else:
            n = coerce_number(v)
            if is_error(n):
                return n
            total += n
    return total


def _collect_numbers(vals):
    """Numbers considered by numeric aggregations. Range: numeric cells only.
    Scalar: coerced (bool->1/0, blank->0, text->#VALUE!)."""
    nums = []
    for v in vals:
        if isinstance(v, RangeValue):
            for c in v.cells:
                if isinstance(c, bool):
                    continue
                if isinstance(c, (int, float)):
                    nums.append(c)
        else:
            n = coerce_number(v)
            if is_error(n):
                return None, n
            nums.append(n)
    return nums, None


def fn_average(vals):
    nums, err = _collect_numbers(vals)
    if err is not None:
        return err
    if not nums:
        return Error("#DIV/0!")
    return sum(nums) / len(nums)


def fn_min(vals):
    nums, err = _collect_numbers(vals)
    if err is not None:
        return err
    return min(nums) if nums else 0


def fn_max(vals):
    nums, err = _collect_numbers(vals)
    if err is not None:
        return err
    return max(nums) if nums else 0


def fn_count(vals):
    count = 0
    for v in vals:
        if isinstance(v, RangeValue):
            for c in v.cells:
                if isinstance(c, bool):
                    continue
                if isinstance(c, (int, float)):
                    count += 1
        else:
            if isinstance(v, bool) or isinstance(v, (int, float)):
                count += 1
            elif v is BLANK:
                pass
            else:  # text scalar
                return Error("#VALUE!")
    return count


def fn_counta(vals):
    count = 0
    for v in vals:
        if isinstance(v, RangeValue):
            for c in v.cells:
                if c is not BLANK:
                    count += 1
        else:
            if v is not BLANK:
                count += 1
    return count


def fn_concat(vals):
    parts = []
    for v in vals:
        if isinstance(v, RangeValue):
            for c in v.cells:
                if c is BLANK:
                    continue
                t = coerce_text(c)
                if is_error(t):
                    return t
                parts.append(t)
        else:
            t = coerce_text(v)
            if is_error(t):
                return t
            parts.append(t)
    return "".join(parts)


def _bool_values(vals):
    """Boolean values for AND/OR. Scalar: coerce_bool (blank->FALSE, text->err).
    Range: numeric/bool cells only (blank/text ignored)."""
    out = []
    for v in vals:
        if isinstance(v, RangeValue):
            for c in v.cells:
                if isinstance(c, bool):
                    out.append(c)
                elif isinstance(c, (int, float)):
                    out.append(c != 0)
        else:
            b = coerce_bool(v)
            if is_error(b):
                return None, b
            out.append(b)
    return out, None


def fn_and(vals):
    bools, err = _bool_values(vals)
    if err is not None:
        return err
    if not bools:
        return Error("#VALUE!")
    return all(bools)


def fn_or(vals):
    bools, err = _bool_values(vals)
    if err is not None:
        return err
    if not bools:
        return Error("#VALUE!")
    return any(bools)


def fn_not(vals):
    b = coerce_bool(vals[0])
    if is_error(b):
        return b
    return not b


def fn_round(vals):
    x = coerce_number(vals[0])
    if is_error(x):
        return x
    n = coerce_number(vals[1])
    if is_error(n):
        return n
    n = int(n)
    try:
        with localcontext() as ctx:
            ctx.prec = 50
            q = Decimal(1).scaleb(-n)
            d = Decimal(repr(float(x))).quantize(q, rounding=ROUND_HALF_UP)
        r = float(d)
    except Exception:
        return Error("#NUM!")
    if r == 0:
        r = 0.0
    return r


def fn_mod(vals):
    a = coerce_number(vals[0])
    if is_error(a):
        return a
    b = coerce_number(vals[1])
    if is_error(b):
        return b
    if b == 0:
        return Error("#DIV/0!")
    return a - b * math.floor(a / b)


def fn_power(vals):
    a = coerce_number(vals[0])
    if is_error(a):
        return a
    b = coerce_number(vals[1])
    if is_error(b):
        return b
    return op_power(a, b)


def fn_abs(vals):
    x = coerce_number(vals[0])
    if is_error(x):
        return x
    return abs(x)


def fn_int(vals):
    x = coerce_number(vals[0])
    if is_error(x):
        return x
    return math.floor(x)


def fn_sqrt(vals):
    x = coerce_number(vals[0])
    if is_error(x):
        return x
    if x < 0:
        return Error("#NUM!")
    return math.sqrt(x)


def fn_len(vals):
    s = coerce_text(vals[0])
    if is_error(s):
        return s
    return len(s)


def _count_arg(v):
    n = coerce_number(v)
    if is_error(n):
        return None, n
    return int(n), None


def fn_left(vals):
    s = coerce_text(vals[0])
    if is_error(s):
        return s
    n, err = _count_arg(vals[1])
    if err is not None:
        return err
    if n < 0:
        return Error("#VALUE!")
    return s[:n]


def fn_right(vals):
    s = coerce_text(vals[0])
    if is_error(s):
        return s
    n, err = _count_arg(vals[1])
    if err is not None:
        return err
    if n < 0:
        return Error("#VALUE!")
    if n == 0:
        return ""
    return s[-n:]


def fn_mid(vals):
    s = coerce_text(vals[0])
    if is_error(s):
        return s
    start, err = _count_arg(vals[1])
    if err is not None:
        return err
    length, err = _count_arg(vals[2])
    if err is not None:
        return err
    if start < 1 or length < 0:
        return Error("#VALUE!")
    return s[start - 1:start - 1 + length]


def fn_upper(vals):
    s = coerce_text(vals[0])
    if is_error(s):
        return s
    return s.upper()


def fn_lower(vals):
    s = coerce_text(vals[0])
    if is_error(s):
        return s
    return s.lower()


def fn_trim(vals):
    s = coerce_text(vals[0])
    if is_error(s):
        return s
    return re.sub(r" +", " ", s).strip(" ")


EAGER_FUNCS = {
    "SUM": fn_sum, "AVERAGE": fn_average, "MIN": fn_min, "MAX": fn_max,
    "COUNT": fn_count, "COUNTA": fn_counta, "CONCAT": fn_concat,
    "AND": fn_and, "OR": fn_or, "NOT": fn_not,
    "ROUND": fn_round, "MOD": fn_mod, "POWER": fn_power,
    "ABS": fn_abs, "INT": fn_int, "SQRT": fn_sqrt, "LEN": fn_len,
    "LEFT": fn_left, "RIGHT": fn_right, "MID": fn_mid,
    "UPPER": fn_upper, "LOWER": fn_lower, "TRIM": fn_trim,
}


# --------------------------------------------------------------------------- #
# Evaluator
# --------------------------------------------------------------------------- #
class Evaluator:
    def __init__(self, rows, cols, get_cell):
        self.rows = rows
        self.cols = cols
        self.get_cell = get_cell  # (col,row) -> internal value

    def eval(self, node):
        tag = node[0]
        if tag == "num":
            return node[1]
        if tag == "str":
            return node[1]
        if tag == "bool":
            return node[1]
        if tag == "nameerr":
            return Error("#NAME?")
        if tag == "err":
            return Error(node[1])
        if tag == "ref":
            col, row = node[1]
            if col < 1 or col > self.cols or row < 1 or row > self.rows:
                return Error("#REF!")
            return self.get_cell((col, row))
        if tag == "range":
            return self.eval_range(node[1], node[2])
        if tag == "unary":
            v = self.eval(node[2])
            return op_unary(node[1], v)
        if tag == "binary":
            op = node[1]
            left = self.eval(node[2])
            if op in ("+", "-", "*", "/", "^"):
                return op_arith(op, left, self.eval(node[3]))
            if op == "&":
                return op_concat(left, self.eval(node[3]))
            return op_compare(op, left, self.eval(node[3]))
        if tag == "func":
            return self.eval_func(node[1], node[2])
        raise ParseError("bad node")

    def eval_range(self, p1, p2):
        c1, r1 = p1
        c2, r2 = p2
        cmin, cmax = min(c1, c2), max(c1, c2)
        rmin, rmax = min(r1, r2), max(r1, r2)
        if cmin < 1 or cmax > self.cols or rmin < 1 or rmax > self.rows:
            return Error("#REF!")
        cells = []
        for r in range(rmin, rmax + 1):
            for c in range(cmin, cmax + 1):
                cells.append(self.get_cell((c, r)))
        return RangeValue(cells)

    def eval_func(self, name, arg_nodes):
        if name not in FUNC_ARITY:
            return Error("#NAME?")
        if not check_arity(name, len(arg_nodes)):
            return Error("#VALUE!")

        if name == "IF":
            cond = self.eval(arg_nodes[0])
            b = coerce_bool(cond)
            if is_error(b):
                return b
            return self.eval(arg_nodes[1] if b else arg_nodes[2])

        if name == "IFERROR":
            v = self.eval(arg_nodes[0])
            if isinstance(v, RangeValue):
                v = Error("#VALUE!")
            if is_error(v):
                fb = self.eval(arg_nodes[1])
                if isinstance(fb, RangeValue):
                    return Error("#VALUE!")
                return fb
            return v

        # Eager functions: evaluate all args left-to-right, then propagate the
        # first error found (scalar or inside a range, row-major).
        vals = [self.eval(a) for a in arg_nodes]
        err = first_arg_error(vals)
        if err is not None:
            return err
        return EAGER_FUNCS[name](vals)


# --------------------------------------------------------------------------- #
# Iterative Tarjan SCC (deps-first output order)
# --------------------------------------------------------------------------- #
def tarjan_scc(nodes, succ):
    index = {}
    low = {}
    on_stack = set()
    stack = []
    counter = [0]
    result = []

    for start in nodes:
        if start in index:
            continue
        work = [(start, 0)]
        while work:
            node, pi = work[-1]
            if pi == 0:
                index[node] = counter[0]
                low[node] = counter[0]
                counter[0] += 1
                stack.append(node)
                on_stack.add(node)
            recurse = False
            succs = succ.get(node, ())
            i = pi
            while i < len(succs):
                w = succs[i]
                if w not in index:
                    work[-1] = (node, i + 1)
                    work.append((w, 0))
                    recurse = True
                    break
                elif w in on_stack:
                    if index[w] < low[node]:
                        low[node] = index[w]
                i += 1
            if recurse:
                continue
            if low[node] == index[node]:
                comp = []
                while True:
                    w = stack.pop()
                    on_stack.discard(w)
                    comp.append(w)
                    if w == node:
                        break
                result.append(comp)
            work.pop()
            if work:
                parent = work[-1][0]
                if low[node] < low[parent]:
                    low[parent] = low[node]
    return result


# --------------------------------------------------------------------------- #
# Top-level compute
# --------------------------------------------------------------------------- #
def _canon_literal(raw):
    """Internal value for a non-formula input cell."""
    if raw is None:
        return BLANK
    if isinstance(raw, bool):
        return raw
    if isinstance(raw, (int, float)):
        return raw
    if isinstance(raw, str):
        return raw
    return Error("#VALUE!")


def _to_json(v):
    """Canonicalize an internal value to JSON output form."""
    if is_error(v):
        return v.code
    if isinstance(v, bool):
        return v
    if v is BLANK:
        return None
    if isinstance(v, RangeValue):
        return "#VALUE!"
    if isinstance(v, float):
        if v.is_integer():
            return int(v)
        return v
    return v


def compute(data):
    rows = data.get("rows")
    cols = data.get("cols")
    cells = data.get("cells", {})
    if not isinstance(rows, int) or not isinstance(cols, int):
        raise ValueError("rows and cols are required integers")

    # Classify cells.
    key_by_coord = {}          # (col,row) -> original key string
    original_keys = list(cells.keys())
    literal_values = {}        # (col,row) -> internal value
    formula_ast = {}           # (col,row) -> AST (or ('err', token))
    coord_of_key = {}          # original key -> (col,row)

    for key in original_keys:
        coord = parse_addr(key)
        coord_of_key[key] = coord
        key_by_coord[coord] = key
        raw = cells[key]
        if isinstance(raw, str) and raw.startswith("="):
            try:
                formula_ast[coord] = parse_formula(raw[1:])
            except (ParseError, ValueError):
                formula_ast[coord] = ("err", "#ERROR!")
        else:
            literal_values[coord] = _canon_literal(raw)

    formula_coords = set(formula_ast.keys())

    # Build dependency graph among formula cells (edges: cell -> formula deps).
    succ = {}
    for coord, ast in formula_ast.items():
        succ[coord] = _formula_deps(ast, formula_coords, cols, rows)

    order = tarjan_scc(list(formula_coords), succ)

    formula_values = {}

    def get_cell(coord):
        if coord in formula_values:
            return formula_values[coord]
        if coord in literal_values:
            return literal_values[coord]
        return BLANK  # in-bounds empty cell

    ev = Evaluator(rows, cols, get_cell)

    for comp in order:
        is_cycle = len(comp) > 1 or (comp[0] in succ.get(comp[0], ()))
        if is_cycle:
            for c in comp:
                formula_values[c] = Error("#CIRCULAR!")
            continue
        coord = comp[0]
        try:
            v = ev.eval(formula_ast[coord])
        except RecursionError:
            v = Error("#ERROR!")
        if isinstance(v, RangeValue):
            v = Error("#VALUE!")
        elif v is BLANK:
            v = 0
        formula_values[coord] = v

    # Assemble output using the ORIGINAL key set.
    out = {}
    for key in original_keys:
        coord = coord_of_key[key]
        if coord in formula_values:
            out[key] = _to_json(formula_values[coord])
        else:
            out[key] = _to_json(literal_values[coord])
    return out


def _formula_deps(ast, formula_coords, cols, rows):
    """Structural dependency edges: which *formula* cells this AST references."""
    deps = []
    seen = set()

    def add(coord):
        if coord in formula_coords and coord not in seen:
            seen.add(coord)
            deps.append(coord)

    def walk(node):
        tag = node[0]
        if tag == "ref":
            add(node[1])
        elif tag == "range":
            (c1, r1), (c2, r2) = node[1], node[2]
            cmin, cmax = min(c1, c2), max(c1, c2)
            rmin, rmax = min(r1, r2), max(r1, r2)
            if cmin < 1 or cmax > cols or rmin < 1 or rmax > rows:
                return
            for r in range(rmin, rmax + 1):
                for c in range(cmin, cmax + 1):
                    add((c, r))
        elif tag == "unary":
            walk(node[2])
        elif tag == "binary":
            walk(node[2])
            walk(node[3])
        elif tag == "func":
            for a in node[2]:
                walk(a)

    walk(ast)
    return deps


def main():
    raw = sys.stdin.buffer.read().decode("utf-8")
    data = json.loads(raw)
    result = compute(data)
    out = json.dumps(result, ensure_ascii=False, separators=(",", ":"),
                     allow_nan=False, sort_keys=True)
    sys.stdout.buffer.write(out.encode("utf-8"))
    sys.stdout.buffer.write(b"\n")


if __name__ == "__main__":
    main()
